package com.mycompany.medical;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Microsoft
 */
public class Login extends javax.swing.JFrame { 
    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
        this.setSize(new java.awt.Dimension(709, 455));
         // If you want to make it non-resizable
         setLocationRelativeTo(null);
        this.setResizable(false);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jtuser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        show = new javax.swing.JCheckBox();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" User id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(470, 170, 80, 31);

        jSeparator2.setBackground(new java.awt.Color(102, 204, 255));
        jSeparator2.setForeground(new java.awt.Color(102, 204, 255));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(440, 220, 180, 10);

        jLabel3.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(480, 220, 77, 24);

        jtuser.setBackground(new java.awt.Color(242, 242, 242));
        jtuser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtuserActionPerformed(evt);
            }
        });
        getContentPane().add(jtuser);
        jtuser.setBounds(440, 200, 177, 24);

        jSeparator1.setBackground(new java.awt.Color(102, 204, 255));
        jSeparator1.setForeground(new java.awt.Color(102, 204, 255));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(440, 260, 180, 10);

        pass.setBackground(new java.awt.Color(242, 242, 242));
        pass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pass.setFocusCycleRoot(true);
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        getContentPane().add(pass);
        pass.setBounds(440, 240, 180, 24);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1.setText("Show Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(550, 270, 80, 20);

        show.setBackground(new java.awt.Color(255, 255, 255));
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        getContentPane().add(show);
        show.setBounds(530, 270, 20, 20);

        button1.setBackground(new java.awt.Color(242, 242, 242));
        button1.setFont(new java.awt.Font("MV Boli", 1, 12)); // NOI18N
        button1.setLabel("Login as Admin");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(470, 300, 150, 30);

        button2.setBackground(new java.awt.Color(242, 242, 242));
        button2.setFont(new java.awt.Font("MV Boli", 1, 12)); // NOI18N
        button2.setLabel("Login as Lab Technician");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2logActionPerformed(evt);
            }
        });
        getContentPane().add(button2);
        button2.setBounds(470, 340, 150, 30);

        button3.setBackground(new java.awt.Color(242, 242, 242));
        button3.setFont(new java.awt.Font("MV Boli", 1, 12)); // NOI18N
        button3.setLabel("Log Out");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3logActionPerformed(evt);
            }
        });
        getContentPane().add(button3);
        button3.setBounds(470, 380, 150, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Microsoft\\Desktop\\medical\\src\\main\\java\\image\\image23 (3).jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 710, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:

        if (show.isSelected()) {
            // Show the password
            pass.setEchoChar((char) 0);
        }

        if (!show.isSelected()) {
            // Show the password
            pass.setEchoChar('*');
        }
    }//GEN-LAST:event_showActionPerformed

    private void button3logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3logActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_button3logActionPerformed

    private void button2logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2logActionPerformed
        if(jtuser.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out User ID ");
        }
        else if (pass.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out Password");
        }
      
        else if (jtuser.getText().contains("2222")&&pass.getText().contains("Lab123")){
            JOptionPane.showMessageDialog(null, "Login Successful");

            TechnicianMenu u= new  TechnicianMenu();
            this.setVisible(false);
            u.setVisible(true);

        }
        else{
            JOptionPane.showMessageDialog(null, "Wrong User ID or Password!!!","Message",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_button2logActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        if(jtuser.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out User ID ");
        }
        else if (pass.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out Password");
        }
        else if (jtuser.getText().contains("1211515")&&pass.getText().contains("Admin123")){
            JOptionPane.showMessageDialog(null, "Login Successful");

            admin a= new  admin();
            this.setVisible(false);
            a.setVisible(true);
        }
        // else if (jtuser.getText().contains("2222")&&pass.getText().contains("Lab123")){
            //     JOptionPane.showMessageDialog(null, "Login Successful");

            //}
        else{
            JOptionPane.showMessageDialog(null, "Wrong User ID or Password!!!","Message",JOptionPane.ERROR_MESSAGE);
        }
          
    }//GEN-LAST:event_logActionPerformed

    private void jtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtuserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jtuser;
    private javax.swing.JPasswordField pass;
    private javax.swing.JCheckBox show;
    // End of variables declaration//GEN-END:variables
}

    
    
    
    
    
    
    
    
    
    
