package com.mycompany.medical;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.ParseException;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.text.SimpleDateFormat;
import java.util.Date;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Microsoft
 */
public class patientFrame extends javax.swing.JFrame {
    public String Ip;
    /**
     * Creates new form patientFrame
     */
    public patientFrame() {
        initComponents();
         this.setSize(new java.awt.Dimension(970, 590));
         // If you want to make it non-resizable
         setLocationRelativeTo(null);
        this.setResizable(false);
        
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        showButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        backButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Patient ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 20, 79, 22);

        jTextField1.setBackground(new java.awt.Color(242, 242, 242));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(150, 20, 133, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Patient FirstName");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 60, 119, 20);

        jTextField2.setBackground(new java.awt.Color(242, 242, 242));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(150, 60, 133, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Patient LastName");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 100, 130, 20);

        jTextField3.setBackground(new java.awt.Color(242, 242, 242));
        jTextField3.setToolTipText("");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(150, 100, 133, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Phone Number");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 20, 100, 20);

        jTextField4.setBackground(new java.awt.Color(242, 242, 242));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(400, 20, 130, 22);

        addButton.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        addButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Microsoft\\Desktop\\medical\\src\\main\\java\\image\\medical (2.jpg")); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(570, 100, 100, 30);

        updateButton.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        updateButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Microsoft\\Desktop\\medical\\src\\main\\image\\refresh (1).jpg")); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton);
        updateButton.setBounds(570, 140, 100, 30);

        deleteButton.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        deleteButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Microsoft\\Desktop\\medical\\src\\main\\java\\image\\delete.png")); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton);
        deleteButton.setBounds(680, 100, 100, 30);

        showButton.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        showButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Microsoft\\Desktop\\medical\\src\\main\\image\\search1.jpg")); // NOI18N
        showButton.setText("Show All Patient");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });
        getContentPane().add(showButton);
        showButton.setBounds(300, 160, 150, 30);

        resetButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Microsoft\\Desktop\\medical\\src\\main\\image\\images (20) (1).jpg")); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton);
        resetButton.setBounds(790, 100, 100, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 60, 90, 20);

        jTextField5.setBackground(new java.awt.Color(242, 242, 242));
        getContentPane().add(jTextField5);
        jTextField5.setBounds(400, 60, 130, 22);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Email");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 100, 67, 20);

        jTextField6.setBackground(new java.awt.Color(242, 242, 242));
        getContentPane().add(jTextField6);
        jTextField6.setBounds(400, 100, 130, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Gender");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(560, 20, 59, 20);

        jComboBox1.setBackground(new java.awt.Color(242, 242, 242));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        jComboBox1.setSelectedIndex(-1);
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(660, 20, 143, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Date_of_Birth");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(560, 60, 89, 20);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(660, 60, 144, 22);

        backButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Microsoft\\Desktop\\medical\\src\\main\\java\\image\\previous1.jpg")); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(10, 510, 129, 46);

        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Microsoft\\Desktop\\medical\\src\\main\\java\\image\\viewUser.png")); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton);
        searchButton.setBounds(10, 160, 110, 30);

        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtsearch);
        txtsearch.setBounds(130, 160, 160, 30);

        jTable1.setBackground(new java.awt.Color(242, 242, 242));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PatientID", "FirstName", "LastName", "PhoneNumber", "Address", "Email", "Gender", "DareOfBirth"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 200, 860, 260);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Microsoft\\Desktop\\medical\\src\\main\\image\\loadd (1) (2).jpg")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 970, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        new TechnicianMenu().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
    try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con= DriverManager.getConnection(connInfo,"shahd12","shahd1923");
            con.setAutoCommit(false);
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
String formattedDate = dateFormat.format(this.jDateChooser1.getDate());

    String qry = "insert into medicallab.\"Patient\" values ("+this.jTextField1.getText() +",'"+this.jTextField2.getText()+"',"
   + "'"+this.jTextField3.getText()+"',"+this.jTextField4.getText()+
    ",'"+this.jTextField5.getText()+"','"+this.jTextField6.getText()+"','"+this.jComboBox1.getSelectedItem()+"','"+formattedDate+"')";
    Statement st = con.createStatement();
        st.executeUpdate(qry);  
        con.commit();
        con.close();
        JOptionPane.showConfirmDialog(null, "Successfully added");
        } catch (Exception ex) {
            //Logger.getLogger(patientFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(rootPane, ex.toString());
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
 try {
            // TODO add your handling code here:            
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo ="jdbc:postgresql://localhost:5432/postgres";
            Connection conn =DriverManager.getConnection(connInfo,"shahd12","shahd1923");
            //conn.setAutoCommit(false);
            String sql = "SELECT * FROM medicallab.\"Patient\"";
            Statement stmt =conn.createStatement();        
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()){
         String PatientID = String.valueOf(rs.getInt(1));
         String first_name =rs.getString(2);
          String last_name =rs.getString(3); 
          String phone_number = rs.getString(4);
           String address =rs.getString(5);
         String email = rs.getString(6);
          String gender = rs.getString(7);
          String date_of_birth =  String.valueOf(rs.getDate(8));
           
              String tbdata[] = {PatientID , first_name,last_name, phone_number, address,email,gender,date_of_birth};
              DefaultTableModel tbModel = (DefaultTableModel)jTable1.getModel();
              tbModel.addRow(tbdata);                          
                      }                    
        }
        catch (SQLException ex) {
            //Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null, ex.toString());
        }
     

        // TODO add your handling code here:
    }//GEN-LAST:event_showButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
 DefaultTableModel m2 = (DefaultTableModel)jTable1.getModel();
 SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
String formattedDate = dateFormat.format(this.jDateChooser1.getDate());
         m2.setValueAt(jTextField2.getText(), jTable1.getSelectedRow(), 1);
         m2.setValueAt(jTextField3.getText(), jTable1.getSelectedRow(), 2);  
         m2.setValueAt(jTextField4.getText(), jTable1.getSelectedRow(), 3);
         m2.setValueAt(jTextField5.getText(), jTable1.getSelectedRow(), 4);   
         m2.setValueAt(jTextField6.getText(), jTable1.getSelectedRow(), 5); 
         m2.setValueAt(jComboBox1.getSelectedItem(), jTable1.getSelectedRow(), 6); 
        
         m2.setValueAt(formattedDate , jTable1.getSelectedRow(), 7);
         
         String query = "UPDATE medicallab.\"Patient\" "
        + "SET \"first_name\"='" + jTextField2.getText() + "'"
        + ", \"last_name\"='" + jTextField3.getText() + "'"
        + ", \"phone_number\"='" + jTextField4.getText() + "'"           
        + ", \"address\"='" + jTextField5.getText() + "'"
        + ", \"email\"='" + jTextField6.getText() + "'"
        + ", \"gender\"='" + jComboBox1.getSelectedItem() + "'" 
        + ", \"date_of_birth\"='" + formattedDate + "'"        
        + " WHERE \"PatientID\"=" + Ip;             
try {
    String connInfo = "jdbc:postgresql://localhost:5432/postgres";
    Connection conn = DriverManager.getConnection(connInfo, "shahd12", "shahd1923");
    Statement st = conn.createStatement();
    st.executeUpdate(query);
    JOptionPane.showMessageDialog(this, "Update successfully!");
} catch (Exception ex) {
    ex.printStackTrace();
}
  

    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
 try{
        String connInfo ="jdbc:postgresql://localhost:5432/postgres";
        Connection con= DriverManager.getConnection(connInfo,"shahd12","shahd1923");
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
int selectedRow = jTable1.getSelectedRowCount();
if (selectedRow == 0) {
    JOptionPane.showMessageDialog(this, "Please selected Single Row For Deleted.");
    
} else if (selectedRow >0){   
    
    String query = "DELETE FROM medicallab.\"Patient\" WHERE \"Patient\".\"PatientID\"="+Ip;   
        Statement st = con.createStatement();
        st.executeUpdate(query);
    JOptionPane.showMessageDialog(this, "Deleted successfully!");
    model.removeRow(jTable1.getSelectedRow());
}
else{  JOptionPane.showMessageDialog(this, "Please selected Single Row For Deleted.");
}  } catch (Exception ex) {
        ex.printStackTrace();
    }

    }//GEN-LAST:event_deleteButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
       DefaultTableModel ob = (DefaultTableModel) jTable1.getModel();
    TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
    jTable1.setRowSorter(obj);
    obj.setRowFilter(RowFilter.regexFilter(txtsearch.getText()));
    }//GEN-LAST:event_searchButtonActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        DefaultTableModel ob = (DefaultTableModel) jTable1.getModel();
    TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
    jTable1.setRowSorter(obj);
    obj.setRowFilter(RowFilter.regexFilter(txtsearch.getText()));
    }//GEN-LAST:event_txtsearchKeyReleased

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
       jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jComboBox1.setSelectedItem("");
        jDateChooser1.setDate(null);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            DefaultTableModel m1 = (DefaultTableModel)jTable1.getModel();
            Ip=m1.getValueAt(jTable1.getSelectedRow(),0).toString();
            String t =m1.getValueAt(jTable1.getSelectedRow(),0).toString();
            jTextField1.setText(t);
            jTextField2.setText( m1.getValueAt(jTable1.getSelectedRow(),1).toString());
            jTextField3.setText(  m1.getValueAt(jTable1.getSelectedRow(),2).toString());
            jTextField4.setText(  m1.getValueAt(jTable1.getSelectedRow(),3).toString());
            // String quan = m1.getValueAt(jTable1.getSelectedRow(),3).toString();
            //quantity.setText(quan);
            String p =m1.getValueAt(jTable1.getSelectedRow(),4).toString();
            jTextField5.setText(p);
            String E =m1.getValueAt(jTable1.getSelectedRow(),5).toString();
            jTextField6.setText(E);
            
            String ss = m1.getValueAt(jTable1.getSelectedRow(),6).toString();
             
            Object a = ss;
           jComboBox1.setSelectedItem(a);
           // String d =m1.getValueAt(jTable1.getSelectedRow(),6).toString();
            //jComboBox1.addItem(d);
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)m1.getValueAt(jTable1.getSelectedRow(),7).toString());
            jDateChooser1.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(patientFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton showButton;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
