/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.medical;

import com.mycompany.medical.TechnicianMenu;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Farah
 */
public class technician extends javax.swing.JFrame {

    public String It;
    /**
     * Creates new form technician
     */
    public technician() {
        initComponents();
        this.setSize(new java.awt.Dimension(960, 475));
         // If you want to make it non-resizable
         setLocationRelativeTo(null);
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        f4 = new java.awt.TextField();
        jLabel5 = new javax.swing.JLabel();
        f5 = new java.awt.TextField();
        jLabel7 = new javax.swing.JLabel();
        f6 = new java.awt.TextField();
        jLabel6 = new javax.swing.JLabel();
        f2 = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        f1 = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        f3 = new java.awt.TextField();
        deletedButton3 = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        addbutton1 = new java.awt.Button();
        showAllButton2 = new javax.swing.JButton();
        UbdatedButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(f4);
        f4.setBounds(380, 30, 108, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Phone Number:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 30, 110, 20);
        getContentPane().add(f5);
        f5.setBounds(380, 60, 108, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Gmail :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(310, 60, 70, 20);
        getContentPane().add(f6);
        f6.setBounds(380, 90, 108, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Address:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 90, 63, 24);

        f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActionPerformed(evt);
            }
        });
        getContentPane().add(f2);
        f2.setBounds(150, 30, 95, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("TechID :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 30, 51, 16);
        getContentPane().add(f1);
        f1.setBounds(150, 60, 95, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("First Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 60, 80, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Last Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 90, 80, 20);
        getContentPane().add(f3);
        f3.setBounds(150, 90, 95, 20);

        deletedButton3.setBackground(new java.awt.Color(242, 242, 242));
        deletedButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deletedButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Microsoft\\Desktop\\medical\\src\\main\\java\\images\\delete.png")); // NOI18N
        deletedButton3.setText("Delete");
        deletedButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deletedButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletedButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(deletedButton3);
        deletedButton3.setBounds(200, 180, 124, 40);

        resetButton.setBackground(new java.awt.Color(242, 242, 242));
        resetButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        resetButton.setText("Reset");
        resetButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton);
        resetButton.setBounds(540, 80, 90, 40);

        addbutton1.setBackground(new java.awt.Color(153, 204, 255));
        addbutton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        addbutton1.setLabel("Save");
        addbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbutton1ActionPerformed(evt);
            }
        });
        getContentPane().add(addbutton1);
        addbutton1.setBounds(540, 30, 90, 40);

        showAllButton2.setBackground(new java.awt.Color(242, 242, 242));
        showAllButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showAllButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Microsoft\\Desktop\\medical\\src\\main\\java\\images\\labt.png")); // NOI18N
        showAllButton2.setText("Show All ");
        showAllButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        showAllButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(showAllButton2);
        showAllButton2.setBounds(20, 180, 160, 40);

        UbdatedButton4.setBackground(new java.awt.Color(242, 242, 242));
        UbdatedButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UbdatedButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Microsoft\\Desktop\\medical\\src\\main\\java\\images\\refresh.jpg")); // NOI18N
        UbdatedButton4.setText("Update");
        UbdatedButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UbdatedButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbdatedButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(UbdatedButton4);
        UbdatedButton4.setBounds(340, 180, 140, 40);

        jButton1.setBackground(new java.awt.Color(242, 242, 242));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Microsoft\\Desktop\\medical\\src\\main\\java\\image\\previous1.jpg")); // NOI18N
        jButton1.setText("Back");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 400, 120, 30);

        jTable1.setBackground(new java.awt.Color(242, 242, 242));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TechnicianID", "First_Name", "Last_Name", "Phone_Number", "Email", "Address"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 230, 500, 160);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Microsoft\\Desktop\\medical\\src\\main\\java\\image\\images (8) (1).jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 960, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new TechnicianMenu().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbutton1ActionPerformed
        // TODO add your handling code here:
       if(f1.getText().equals("")||f2.getText().equals("")||f3.getText().equals("")||f4.getText().equals("")||f5.getText().equals("")||f6.getText().equals("")){
       JOptionPane.showMessageDialog(null,"Please Enter All Data");}
       else{
        
        try {
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo, "shahd12","shahd1923");
            con.setAutoCommit(false);   
            
        String qry="INSERT INTO medicallab.\"LabTechnician\" values("+this.f2.getText()+",'"+this.f1.getText()+"','"+this.f3.getText()+"',"+this.f4.getText()+",'"+this.f5.getText()+"','"+this.f6.getText()+"')";
        Statement stmt= con.createStatement();
            stmt.executeUpdate(qry);
            con.commit(); //save the data manually
            con.close();//heek the data is in DB
JOptionPane.showConfirmDialog(null, "Successfully added");
        } 
        catch (Exception ex)
        {
           // Logger.getLogger(NewTechnichian.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showConfirmDialog(rootPane, ex.toString());
        }}
    }//GEN-LAST:event_addbutton1ActionPerformed

    private void showAllButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllButton2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo ="jdbc:postgresql://localhost:5432/postgres";
            Connection conn =DriverManager.getConnection(connInfo,"shahd12","shahd1923");
            //conn.setAutoCommit(false);
            String sql = "SELECT * FROM medicallab.\"LabTechnician\"";
            Statement stmt =conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()){
                String TechnicianID = String.valueOf(rs.getInt(1));
                String first_name =rs.getString(2);
                String last_name =rs.getString(3);              
                String phone_number = rs.getString(4); 
                String email = rs.getString(5);
                String address =rs.getString(6);

                String tbdata[] = {TechnicianID  , first_name,last_name,phone_number,email, address};
                DefaultTableModel tbModel = (DefaultTableModel)jTable1.getModel();
                tbModel.addRow(tbdata);
            }
        }
        catch (SQLException ex) {
            //Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null, ex.toString());
        }
    }//GEN-LAST:event_showAllButton2ActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
       f1.setText("");
        f2.setText("");
        f3.setText("");
        f4.setText("");
        f5.setText("");
        f6.setText("");
       
    }//GEN-LAST:event_resetButtonActionPerformed

    private void deletedButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletedButton3ActionPerformed
 try{
        String connInfo ="jdbc:postgresql://localhost:5432/postgres";
        Connection con= DriverManager.getConnection(connInfo,"shahd12","shahd1923");
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
int selectedRow = jTable1.getSelectedRowCount();
if (selectedRow == 0) {
    JOptionPane.showMessageDialog(this, "Please selected Single Row For Deleted.");
} else if (selectedRow >0){       
    String query = "DELETE FROM medicallab.\"LabTechnician\" WHERE \"LabTechnician\".\"TechnicianID\"="+It;  
        Statement st = con.createStatement();
        st.executeUpdate(query);
    JOptionPane.showMessageDialog(this, "Deleted successfully!");
    model.removeRow(jTable1.getSelectedRow());
}
else{  JOptionPane.showMessageDialog(this, "Please selected Single Row For Deleted.");
}  } catch (Exception ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_deletedButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    DefaultTableModel m1 = (DefaultTableModel)jTable1.getModel();
        It=m1.getValueAt(jTable1.getSelectedRow(),0).toString();
        String t =m1.getValueAt(jTable1.getSelectedRow(),0).toString();
        f2.setText(t);
        f1.setText( m1.getValueAt(jTable1.getSelectedRow(),1).toString());
        f3.setText(  m1.getValueAt(jTable1.getSelectedRow(),2).toString());
         f4.setText(  m1.getValueAt(jTable1.getSelectedRow(),3).toString());
       // String quan = m1.getValueAt(jTable1.getSelectedRow(),3).toString();
        //quantity.setText(quan);
        String p =m1.getValueAt(jTable1.getSelectedRow(),4).toString();
        f5.setText(p);
         
          f6.setText(  m1.getValueAt(jTable1.getSelectedRow(),5).toString());
              // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void UbdatedButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbdatedButton4ActionPerformed
       DefaultTableModel m2 = (DefaultTableModel) jTable1.getModel();
m2.setValueAt(f1.getText(), jTable1.getSelectedRow(), 1);
m2.setValueAt(f3.getText(), jTable1.getSelectedRow(), 2);
m2.setValueAt(f4.getText(), jTable1.getSelectedRow(), 3);
m2.setValueAt(f5.getText(), jTable1.getSelectedRow(), 4);
m2.setValueAt(f6.getText(), jTable1.getSelectedRow(), 5);


String query = "UPDATE medicallab.\"LabTechnician\" "
        + "SET \"first_name\"='" + f1.getText() + "'"
        + ", \"last_name\"='" + f3.getText() + "'"
        + ", \"phone_number\"='" + f4.getText() + "'" // Assuming phone_number is a string, update it accordingly
        + ", \"email\"='" + f5.getText() + "'"
        + ", \"address\"='" + f6.getText() + "'"
        + " WHERE \"TechnicianID\"=" + It;
try {
    String connInfo = "jdbc:postgresql://localhost:5432/postgres";
    Connection conn = DriverManager.getConnection(connInfo, "shahd12", "shahd1923");
    Statement st = conn.createStatement();
    int rowsUpdated = st.executeUpdate(query);
    if (rowsUpdated > 0) {
        JOptionPane.showMessageDialog(this, "Update successfully!");
    } else {
        JOptionPane.showMessageDialog(this, "No records were updated.");
    }
} catch (SQLException ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this, "SQL Error: " + ex.getMessage());
} catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
}
    }//GEN-LAST:event_UbdatedButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(technician.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(technician.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(technician.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(technician.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              new technician().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UbdatedButton4;
    private java.awt.Button addbutton1;
    private javax.swing.JButton deletedButton3;
    private java.awt.TextField f1;
    private java.awt.TextField f2;
    private java.awt.TextField f3;
    private java.awt.TextField f4;
    private java.awt.TextField f5;
    private java.awt.TextField f6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton showAllButton2;
    // End of variables declaration//GEN-END:variables
}
