/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.medical;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Farah
 */
public class Test extends javax.swing.JFrame {
public String Id;
    /**
     * Creates new form Test
     */            
    public Test() {
        initComponents();
        
         this.setSize(new java.awt.Dimension(740, 690));
        
        // If you want to make it non-resizable
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        canvas1 = new java.awt.Canvas();
        testid = new java.awt.TextField();
        label2 = new java.awt.Label();
        pid = new java.awt.TextField();
        label3 = new java.awt.Label();
        textArea1 = new java.awt.TextArea();
        label4 = new java.awt.Label();
        name = new java.awt.TextField();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        did = new java.awt.TextField();
        cost = new java.awt.TextField();
        label7 = new java.awt.Label();
        type = new java.awt.TextField();
        addbutton1 = new java.awt.Button();
        jLabel3 = new javax.swing.JLabel();
        Sid = new javax.swing.JButton();
        UpdateButton2 = new javax.swing.JButton();
        deletedButton3 = new javax.swing.JButton();
        ShowallButton4 = new javax.swing.JButton();
        sdata = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        resetButton = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(802, 389));
        setSize(new java.awt.Dimension(802, 389));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(740, 662));

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("TestID:");

        testid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testidActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("Test Name:");

        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setText("Description:");

        textArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("Cost:");

        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setText("Patient ID :");

        label6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label6.setName("Dr ID :"); // NOI18N
        label6.setText("Doctor ID :");

        label7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label7.setText("Test Type :");

        addbutton1.setBackground(new java.awt.Color(102, 204, 255));
        addbutton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        addbutton1.setLabel("Save");
        addbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbutton1ActionPerformed(evt);
            }
        });

        Sid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Sid.setIcon(new javax.swing.ImageIcon("C:\\Users\\Microsoft\\Desktop\\medical\\src\\main\\java\\images\\s (1).png")); // NOI18N
        Sid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SidActionPerformed(evt);
            }
        });

        UpdateButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UpdateButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Microsoft\\Desktop\\medical\\src\\main\\java\\images\\refresh.jpg")); // NOI18N
        UpdateButton2.setText("Update");
        UpdateButton2.setPreferredSize(new java.awt.Dimension(91, 27));
        UpdateButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButton2ActionPerformed(evt);
            }
        });

        deletedButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deletedButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Microsoft\\Desktop\\medical\\src\\main\\java\\image\\delete.png")); // NOI18N
        deletedButton3.setText("Delete");
        deletedButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletedButton3ActionPerformed(evt);
            }
        });

        ShowallButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ShowallButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Microsoft\\Desktop\\medical\\src\\main\\java\\images\\s (1).png")); // NOI18N
        ShowallButton4.setText("Show All Tests");
        ShowallButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowallButton4ActionPerformed(evt);
            }
        });

        sdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdataActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Search Using ID :");

        backButton.setBackground(new java.awt.Color(242, 242, 242));
        backButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Microsoft\\Desktop\\medical\\src\\main\\java\\image\\previous1.jpg")); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TestID", "Test_Name", "Description", "Test_Type", "PatientID", "DoctorID", "Cost"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        resetButton.setBackground(new java.awt.Color(242, 242, 242));
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Search");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textArea1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(24, 24, 24)
                                            .addComponent(testid, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(did, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(115, 115, 115)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cost, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deletedButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(sdata, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(Sid)))
                                            .addGap(180, 180, 180))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ShowallButton4)))))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addGap(109, 109, 109))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(testid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(did, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addComponent(addbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))))
                            .addComponent(textArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(4, 4, 4)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Sid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sdata)))
                            .addComponent(ShowallButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletedButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        label4.getAccessibleContext().setAccessibleName("cost");
        name.getAccessibleContext().setAccessibleName("cost");
        label5.getAccessibleContext().setAccessibleName("patiant id ");
        label6.getAccessibleContext().setAccessibleName("dr id");
        did.getAccessibleContext().setAccessibleName("dr id ");
        cost.getAccessibleContext().setAccessibleName("cost");
        addbutton1.getAccessibleContext().setAccessibleName("save patient");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testidActionPerformed

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidActionPerformed

    private void addbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbutton1ActionPerformed
     if(testid.getText().equals("")||name.getText().equals("")||type.getText().equals("")||cost.getText().equals("")||pid.getText().equals("")||did.getText().equals("")||textArea1.getText().equals("")){
       JOptionPane.showMessageDialog(null,"Please Enter All Data");}
       else{
 try {
     // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con= DriverManager.getConnection(connInfo,"shahd12","shahd1923");
            con.setAutoCommit(false);
    String qry = "insert into medicallab.\"Test\" values("+this.testid.getText()+",'"+this.name.getText()+"','"+this.textArea1.getText()+"','"+this.type.getText()+"',"+this.pid.getText()+","+this.did.getText()+",'"+this.cost.getText()+"')"; 
    Statement st = con.createStatement();
        st.executeUpdate(qry);  
        con.commit();
        con.close();
        JOptionPane.showConfirmDialog(null, "Successfully added");
        } catch (Exception ex) {          
            JOptionPane.showConfirmDialog(rootPane, ex.toString());
        }     }
    
        
        
        
        
        /*         try {
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo, "shahd12","shahd1923");
            con.setAutoCommit(false);    
        String qry="INSERT INTO medicallab.Test values("+this.testid.getText()+","+this.did.getText()+","+this.pid.getText()+",'"+this.textArea1.getText()+" ',"+this.cost.getText()+",'"+this.name.getText()+"','"+this.type.getText()+"')"  ;
           Statement stmt= con.createStatement();
            stmt.executeUpdate(qry);
            con.commit(); //save the data manually
            con.close();//heek the data is in DB
JOptionPane.showConfirmDialog(null, "Successfully added");
        } 
        catch (Exception ex)
        {
           // Logger.getLogger(NewTechnichian.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showConfirmDialog(rootPane, ex.toString());
        }*/
    }//GEN-LAST:event_addbutton1ActionPerformed

    private void SidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SidActionPerformed
        // TODO add your handling code here:
        String IDD ;
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo ="jdbc:postgresql://localhost:5432/postgres";
            Connection conn =DriverManager.getConnection(connInfo,"shahd12","shahd1923");
            conn.setAutoCommit(false);
           // String sql = "SELECT * FROM medicallab121.\"test\"";
            Statement stmt =conn.createStatement();
        IDD=sdata.getText();
   String sql = "SELECT * FROM medicallab.\"Test\" WHERE \"Test\".\"PatientID\"="+IDD;
ResultSet rs = stmt.executeQuery ( sql);
while(rs.next ()) 
{
                String TestID = String.valueOf(rs.getInt(1));
                String Test_Name =rs.getString(2);
                String Description =rs.getString(3);
                 String Test_Type = rs.getString(4);
                 String PatientID = String.valueOf(rs.getInt(5));
                String DoctorID = String.valueOf(rs.getInt(6));
                String Cost =rs.getString(7);
              
                String tbdata[] = {TestID ,Test_Name,Description,Test_Type,PatientID,DoctorID ,Cost};
                DefaultTableModel tbModel = (DefaultTableModel)jTable1.getModel();
                tbModel.addRow(tbdata);              
        }}
        catch (SQLException ex) {
            //Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null, ex.toString());
        }
    }//GEN-LAST:event_SidActionPerformed

    private void deletedButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletedButton3ActionPerformed
 try{
        String connInfo ="jdbc:postgresql://localhost:5432/postgres";
        Connection con= DriverManager.getConnection(connInfo,"shahd12","shahd1923");
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
int selectedRow = jTable1.getSelectedRowCount();
if (selectedRow == 0) {
    JOptionPane.showMessageDialog(this, "Please selected Single Row For Deleted.");
    
} else if (selectedRow >0){   
    
    String query = "DELETE FROM medicallab.\"Test\" WHERE \"Test\".\"TestID\"="+Id;   
        Statement st = con.createStatement();
        st.executeUpdate(query);
    JOptionPane.showMessageDialog(this, "Deleted successfully!");
    model.removeRow(jTable1.getSelectedRow());
}
else{  JOptionPane.showMessageDialog(this, "Please selected Single Row For Deleted.");
}  } catch (Exception ex) {
        ex.printStackTrace();
    }
            
    }//GEN-LAST:event_deletedButton3ActionPerformed

    private void ShowallButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowallButton4ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo ="jdbc:postgresql://localhost:5432/postgres";
            Connection conn =DriverManager.getConnection(connInfo,"shahd12","shahd1923");
            //conn.setAutoCommit(false);
            String sql = "SELECT * FROM medicallab.\"Test\"";
            Statement stmt =conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()){
                String TestID = String.valueOf(rs.getInt(1));
                String Test_Name =rs.getString(2);
                String Description =rs.getString(3);
                 String Test_Type = rs.getString(4);
                 String PatientID = String.valueOf(rs.getInt(5));
                String DoctorID = String.valueOf(rs.getInt(6));
                String Cost =rs.getString(7);
              
                String tbdata[] = {TestID ,Test_Name,Description,Test_Type,PatientID,DoctorID ,Cost};
                DefaultTableModel tbModel = (DefaultTableModel)jTable1.getModel();
                tbModel.addRow(tbdata);
            }
        }
        catch (SQLException ex) {
            //Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null, ex.toString());
        }
    }//GEN-LAST:event_ShowallButton4ActionPerformed

    private void sdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdataActionPerformed

    private void UpdateButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButton2ActionPerformed
        DefaultTableModel m2 = (DefaultTableModel) jTable1.getModel();
m2.setValueAt(name.getText(), jTable1.getSelectedRow(), 1);
m2.setValueAt(textArea1.getText(), jTable1.getSelectedRow(), 2);
m2.setValueAt(type.getText(), jTable1.getSelectedRow(), 3);
m2.setValueAt(pid.getText(), jTable1.getSelectedRow(), 4);
m2.setValueAt(did.getText(), jTable1.getSelectedRow(), 5);
m2.setValueAt(cost.getText(), jTable1.getSelectedRow(), 6);

String query = "UPDATE medicallab.\"Test\" "
        + "SET \"Test_name\"='" + name.getText() + "'"
        + ", \"description\"='" + textArea1.getText() + "'"
        + ", \"Test_type\"='" + type.getText() + "'"
        + ", \"PatientID\"=" + pid.getText() + ""
        + ", \"DoctorID\"=" + did.getText() + ""
        + ", \"cost\"='" + cost.getText() + "'"
        + " WHERE \"TestID\"=" + Id; // Corrected column name

try {
    String connInfo = "jdbc:postgresql://localhost:5432/postgres";
    Connection conn = DriverManager.getConnection(connInfo, "shahd12", "shahd1923");
    Statement st = conn.createStatement();
    st.executeUpdate(query);
    JOptionPane.showMessageDialog(this, "Update successfully!");
} catch (Exception ex) {
    ex.printStackTrace();
}

    }//GEN-LAST:event_UpdateButton2ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        new TechnicianMenu().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        testid.setText("");
        pid.setText("");
        type.setText("");
        name.setText("");
        did.setText("");
        cost.setText("");
        textArea1.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         DefaultTableModel m1 = (DefaultTableModel)jTable1.getModel();
        Id=m1.getValueAt(jTable1.getSelectedRow(),0).toString();
        String t =m1.getValueAt(jTable1.getSelectedRow(),0).toString();
        testid.setText(t);
        name.setText( m1.getValueAt(jTable1.getSelectedRow(),1).toString());
        textArea1.setText(  m1.getValueAt(jTable1.getSelectedRow(),2).toString());
         type.setText(  m1.getValueAt(jTable1.getSelectedRow(),3).toString());
       // String quan = m1.getValueAt(jTable1.getSelectedRow(),3).toString();
        //quantity.setText(quan);
        String p =m1.getValueAt(jTable1.getSelectedRow(),4).toString();
        pid.setText(p);
         String d =m1.getValueAt(jTable1.getSelectedRow(),5).toString();
        did.setText(d);
 
        cost.setText( m1.getValueAt(jTable1.getSelectedRow(),6).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyPressed

    }//GEN-LAST:event_txtsearchKeyPressed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        DefaultTableModel ob = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
        jTable1.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(txtsearch.getText()));
    }//GEN-LAST:event_txtsearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ShowallButton4;
    private javax.swing.JButton Sid;
    private javax.swing.JButton UpdateButton2;
    private java.awt.Button addbutton1;
    private javax.swing.JButton backButton;
    private java.awt.Canvas canvas1;
    private java.awt.TextField cost;
    private javax.swing.JButton deletedButton3;
    private java.awt.TextField did;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.TextField name;
    private java.awt.TextField pid;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField sdata;
    private java.awt.TextField testid;
    private java.awt.TextArea textArea1;
    private javax.swing.JTextField txtsearch;
    private java.awt.TextField type;
    // End of variables declaration//GEN-END:variables
}
